### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by gobbedy** [bulletmark/cdhist#11]
Hello,

Thank you for sharing your utility. It looks promising.

I'm on Linux (Oracle Linux Server release 7.9).

I'm able to install the python package via pip, but this does not add a ```cdhist``` command.
```$: type cdhist
-bash: type: cdhist: not found
```

I can see the locally installed cdhist.py, but it's not executable. When I made it executable (I doubt I'm supposed to do that, but figured I'd try anyway), I tried running ```cdhist.py -i``` but that just gave me another error:
```
$: /path/to/python38_packages/cdhist/cdhist.py -i
Traceback (most recent call last):
  File "/path/to/python38_packages/cdhist/cdhist.py", line 10, in <module>
    from . import utils
ImportError: cannot import name 'utils'
```

Note: if it's relevant, I installed the package this way:
```python3.8 -m pip install git+https://github.com/bulletmark/cdhist --target=/path/to/python38_packages```

This is how I usually install packages and it has worked for me thus far (I need the ```target``` option because I don't have admin privileges to modify the python install itself).

Any guidance would be greatly appreciated.

**Comment by bulletmark** [comment]
You say here that you are installing cdhist to a non-standard location but then you are complaining that location is not in your PATH?!

However, why are you installing directly from github, and why to an odd location? You don't need admin/root privileges. Just type `python3.8 -m pip install --user cdhist` and then ensure you add  the standard user bin `~/.local/bin` to your PATH.

Note your questions here are really general linux/python/pip questions and not really about any problem with cdhist. Set up your environment correctly and it should work.

**Comment by gobbedy** [comment]
Following your reply I now realize that ```cdhist``` was installed in ```/path/to/python38_packages/bin```. I'm not sure why it should be obvious to me that ```cdhist``` was installed in that directory. There was no indication either in the documentation nor during the installation process that I should find the executable in that directory.

You may want to consider adding a note in your installation or setup steps mentioning where ```cdhist``` is installed, and to add this path to the PATH variable.

To your question as to why I'm installing directly from github: your instructions give as one of two options to clone your github repository and install directly from the cloned repo. So your own instructions suggest installing directly from github as a viable option. So in short, I installed directly from github because I could.

As to your question about my "odd" install location, I do not install anything in my home directory because this is a work environment in which we have limited space in our home directory and we are instructed not to install anything there.

The ```--target``` option is a standard option provided by pip and you should expect your users to optionally use it.

You may also consider using a less antagonizing tone when replying to users asking for help.

**Comment by bulletmark** [comment]
Your first paragraph above is a complaint about `pip` do please don't complain here. My instructions do not say to install as you have and it is not clear why you are using an odd approach. Please explain why you must use `--target` on pip (which I have never seen before) as opposed to the standard user install approach which is `python -m pip install --user cdhist`? Why does that not work for you?

Using `--target` seems to put the bin and the package in the same directory so I am not sure what the point of that is. I'm sorry but if you want to use pip in a non-standard way then you are best to work out how to do that.

**Comment by gobbedy** [comment]
> Your first paragraph above is a complaint about pip do please don't complain here."

No. I was responding to your accusation that
> you are complaining that location is not in your PATH

My response: I made no such complaint. I followed your instructions using a correct pip install flow. The install flow failed because ```cdhist``` was not added to the PATH variable, which was a required step I had no way of knowing about. Your installation instructions do not mention where ```cdhist``` is installed (as it turns out, in the "bin" subdirectory of the python packages directory), nor do they explain that the said bin directory must be added to PATH variable.

None of that is a "complaint about pip".

> Please explain why you must use --target on pip (which I have never seen before) as opposed to the standard user install approach which is python -m pip install --user cdhist?

How is it relevant that you've never seen the ```--target``` option? I have already explained why I used pip's ```target``` option. From my previous response:

> As to your question about my "odd" install location, I do not install anything in my home directory because this is a work environment in which we have limited space in our home directory and we are instructed not to install anything there.

The ```--target``` option lets you install your packages in a custom packages directory when you don't have access to your home directory (or, in my case, have been instructed not to use it). Your lack of knowledge about the ```target``` option does not make it any less viable.

> Using --target seems to put the bin and the package in the same directory so I am not sure what the point of that is. I'm sorry but if you want to use pip in a non-standard way then you are best to work out how to do that.

```--target``` is not non-standard. It is a well established/documented option that is compatible with all major packages.

Your go-to response to user question/comments is blame and accusation.

I'm not interested in your attempts to point fingers. I will not respond to further such fruitless discussion.

**Comment by bulletmark** [comment]
Are you going to answer my question? Why are you not using `python -m pip install --user cdhist`?

**Comment by gobbedy** [comment]
I'm sorry, do you have reading difficulties? I explained it twice. Best of luck.

**Comment by gobbedy** [comment]
Best of luck in your future endeavours.
