### ISSUE TITLE
missing credits?

### ISSUE THREAD

**Issue by glensc** [bulletmark/cdhist#2]
seems this utility is a rewrite of the cdhist provided with bash installation. same options usage and even the variables seem to match.

here's one online copy I was able to found in git repo:
- https://git.savannah.gnu.org/cgit/bash.git/tree/examples/scripts.v2/cdhist.bash?h=bash-4.2

coincidence? or missing credits to previous authors?

**Comment by bulletmark** [comment]
This utility in this repo is 100 % my own work. That code you quote there is written in shell script and looks **nothing** like my Python code here and that is obvious to anybody.

**Comment by glensc** [comment]
not obvious to me, so not anybody. and rewrite means that it's written from scratch, maybe even a different language.
