### ISSUE TITLE
Alternative FZF_ALT_C_COMMAND

### ISSUE THREAD

**Issue by glensc** [bulletmark/cdhist#5]
I got annoyed that alt+c gave me paths that didn't exist, so I made up this command:

```
export FZF_ALT_C_COMMAND='while read path; do test -d "$path" && echo "$path"; done < ~/.cd_history'
```

**Comment by bulletmark** [comment]
Why have you got significant numbers of paths in your history that don't exist? I rarely get any. BTW, `cd -p` (or `cdhist -p`) purges all non-existent paths from your history file so probably more efficient to use that in your command.

**Comment by glensc** [comment]
the reason is irrelevant. but to answer: because I'm reorganizing some files, I move directories and delete directories. why should I `cd` to a directory that doesn't exist? so, those should not be fed to `fzf`.

**Comment by glensc** [comment]
and not significant, only one mis-completion already annoys me. especially as it's offered first, and I don't even know if that option in the list is already moved directory or still in the old path.

**Comment by bulletmark** [comment]
Anyhow, this is not an issue.

**Comment by glensc** [comment]
it's a suggestion!
